name: labAccessDetector
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # Get It
  get_it: ^5.0.6
  # Stacked Architecture
  stacked: ^1.7.7
  # Google Fonts
  google_fonts: ^1.1.1
  # beacon
  flutter_beacon: ^0.3.0
  # local notification
  flutter_local_notifications: ^4.0.1
  # effective dart
  effective_dart: ^1.3.0
  # location_permission
  location_permissions: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
